<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHy7hfd0\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHy7hfd0/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerHy7hfd0.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerHy7hfd0\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerHy7hfd0\appProdProjectContainer([
    'container.build_hash' => 'Hy7hfd0',
    'container.build_id' => 'b7e51ce8',
    'container.build_time' => 1644400742,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHy7hfd0');
