<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHd1xrtt\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHd1xrtt/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerHd1xrtt.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerHd1xrtt\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerHd1xrtt\appProdProjectContainer([
    'container.build_hash' => 'Hd1xrtt',
    'container.build_id' => 'a7a64361',
    'container.build_time' => 1644393890,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHd1xrtt');
