<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU6jsque\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU6jsque/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerU6jsque.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerU6jsque\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerU6jsque\appProdProjectContainer([
    'container.build_hash' => 'U6jsque',
    'container.build_id' => '10250913',
    'container.build_time' => 1644393321,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU6jsque');
